name: ironopen
main: com.github.mpotacon.ironopen.ironopen
version: 0.2
author: mpotacon
description: Open iron-door on right click
commands:
    open:
        description: Opens iron door
        usage: right click iron doors to open
